### ISSUE TITLE
Create LIDAR class for data processing according to the Development Manual

### ISSUE THREAD

**Issue by jkleiber** [Sooner-Competitive-Robotics/robomagellan-2019#24]
The LIDAR sensor has a pretty detailed datasheet posted in the google drive that outlines how to get data from it. We are interested in getting the distance to the nearest obstacle at 0.63 degree increments, and also knowing which direction is forward.

We want to be able to handle the data processing on the raspberry pi so this will end up being part of the SLAM/obstacle detection module on the main board.

For a starting point we need to be able to get the data from the device and output it to the console of the Pi.

**Comment by jkleiber** [comment]
This likely will end up being a python script that will interface with the SLAM/obstacle detection program (which will also be written in python). I am going to write a python class for the data collection/telling the lidar what to do and another script that uses this class to read data about obstacles

**Comment by jkleiber** [comment]
This likely will end up being a python script that will interface with the SLAM/obstacle detection program (which will also be written in python). I am going to write a python class for the data collection/telling the lidar what to do and another script that uses this class to read data about obstacles

**Comment by colton5007** [comment]
http://www.ydlidar.com/download
