### ISSUE TITLE
IMU-GPS Sensor Fusion

### ISSUE THREAD

**Issue by jkleiber** [Sooner-Competitive-Robotics/robomagellan-2019#5]

**Comment by lae111** [comment]
So I didn't follow exactly what you wanted done here. But from researching sensor fusion I think a Kalman Filter is the best option (https://www.bzarg.com/p/how-a-kalman-filter-works-in-pictures/). The math for something like this was decently complicated so I want to make sure you're onboard. Without using a filter I'm not sure exactly what you want done

**Comment by jkleiber** [comment]
Closing this issue as it is a duplicate of #26
